# Generated by Django 5.1 on 2024-08-30 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={},
        ),
        migrations.RemoveField(
            model_name="todo",
            name="author",
        ),
        migrations.AddField(
            model_name="todo",
            name="completed_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="todo/completed_images"
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="todo/no_image/NO-IMAGE.gif",
                null=True,
                upload_to="todo/thumbnails",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
